version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"  # Porta do Vite
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflito entre node_modules do host e container
    environment:
      - NODE_ENV=development
